config/routes.rb
Rails.application.routes.draw do

  root to: 'feeds#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums do
    resources :photos
  end
  resources :photos, :albums, :admins

end

app/views/admins/edit.html.slim
= form_for(@user, url: admin_path(@user.id), html: { method: :put }, namespace:"information") do |form|
  .form-signin
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          - if @user.avatar?
            = image_tag @user.avatar_url(:thumb), id: "img_prev", class: "img-thumbnail avatar"
          - else
            = image_tag "avatar-login.png", id: "img_prev", class: "img-thumbnail avatar"
          = form.file_field :avatar, onchange: "window.readURL(this);", class: "upload-avatar"
    .form-group.basic-information
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          span.text-bold Basic Information
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
          = form.label( t(:firstname))
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          = form.text_field :firstname, class: "form-control"
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
          = form.label( t(:lastname))
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          = form.text_field :lastname, class: "form-control"
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
          = form.label( t(:email))
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          = form.text_field :email, class: "form-control"
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
          = form.label( t(:password))
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          = form.password_field :password, class: "form-control"
    .form-group
      .row
        .col-md-4.col-sm-4.col-4.text-right.text-bold
        .col-md-5.col-sm-6.col-8.offset-col-md-3.offset-col-sm-2
          = form.submit t(:save), class: "save-button"

app/views/admins/index.html.slim
table.table.table-hover.table-responsive-lg
  thead
    tr
      th scope="col"  = t(:firstname)
      th scope="col"  = t(:lastname)
      th scope="col"  = t(:email)
      th scope="col"  = t(:last_login)
      th scope="col"
      th scope="col"
  tbody
    - @users.each do |user|
      tr
        td = user.firstname
        td = user.lastname
        td = user.email
        td = user.last_sign_in_at.strftime(" %I:%M%p %d/%m/%Y")
        td = link_to '<button class="edit-manage-user" type="button">Edit</button>'.html_safe, edit_admin_path(user.id)
        td = link_to '<button class="delete-manage-user" type="button">Delete</button>'.html_safe, admin_path(user.id), method: :delete, data: { confirm: 'Are you sure?' }