config/routes.rb
Rails.application.routes.draw do

  root to: 'feeds#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums do
    resources :photos
  end
  resources :photos, :albums, :admins

end

app/models/album.rb
class Album < ApplicationRecord

  belongs_to :user
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, allow_destroy: true, reject_if: proc { |attributes| attributes['image'].blank? }
  scope :public_mode, -> { where(mode: "Public") }

  validates :title, :description, :mode, presence: true
  validates :title, length: { maximum: 140,
    too_long: "Maximum 140 characters long" }
  validates :description, length: { maximum: 300,
    too_long: "Maximum 300 characters long" }
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    if !current_user.admin
      @albums = current_user.albums.includes(:photos).page(params[:page])
    else
      @albums = Album.all.includes(:photos).page(params[:page])
    end
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user
    if @album.save
      params[:photos][:image].each do |img|
        @photo = @album.photos.new(title:"Image created from album!", description: "No description", mode: "Private", image: img, user_id: current_user.id)
        if @photo.valid?
          @photo.save
        else
          flash[:alert] = @photo.errors.full_messages.join(',')
          return render :new
        end
      end
      redirect_to albums_path
    else
      render :new
    end
  end

  def show
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])
    if @album.update(album_params)
      if params[:photos]
        params[:photos][:image].each do |img|
          @photo = @album.photos.new(title:"Image created from album!", description: "No description", mode: "Private", image: img, user_id: current_user.id)
          if @photo.valid?
            @photo.save
          else
            flash[:alert] = @photo.errors.full_messages.join(',')
            return render :edit
          end
        end
      end
      redirect_to edit_album_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to albums_path
  end

  private
    def album_params
      params.require(:album).permit(:title, :description, :mode, photos_attributes: [:image, :user_id])
    end

end

app/views/albums/_form.html.slim
= form_for album, html: { multipart: true } do |f|
  - if album.errors.any?
    #error_explanation.alert.alert-warning.alert-dismissible.fade.show role="alert"
      h3
        = pluralize(album.errors.count, "error")
        | prohibited this album from being saved:
      ul
        - album.errors.full_messages.each do |message|
          li= message
  .row
    .col-sm-6.col-12
      .form-group
        .text-bold
          = f.label t(:title)
        = f.text_field :title, placeholder: "Album Title", class: "album-title"

      .form-group
        .text-bold
          = f.label t(:mode)
        = f.select "mode",
          options_for_select([ "Public", "Private" ])
    .col-sm-6.col-12
      .form-group
        .text-bold
          = f.label t(:description)
        = f.text_area :description, rows: "4",placeholder: "Album Description"

  .row.all-image-of-album
    - if album.photos.exists?
      - album.photos.each do |image|
        .col-md-3.col-sm-4.col-6.p-0
          = image_tag image.image_url(:thumb), class: "img-thumbnail preview-album-image"
          = link_to image_tag("delete.png", class: "icon-delete"), album_photo_path({album_id: album.id, id: image.id, redirect_path: edit_album_path}), method: :delete, data: { confirm: 'Are you sure?' }, class: "link-delete"

      .col-md-3.col-sm-4.col-6.add-photo-to-album.p-0.gallery
        = image_tag "plus-icon", class: "img-thumbnail icon-plus img-preview"
        = file_field_tag :image, multiple: true, name: "photos[image][]", id: "gallery-photo-add", class: "add-image-area"

    - else
      .col-md-3.col-sm-4.col-6.add-photo-to-album.p-0.gallery
        = image_tag "plus-icon", class: "img-thumbnail icon-plus img-preview"
        = file_field_tag :image, multiple: true, name: "photos[image][]", id: "gallery-photo-add", class: "add-image-area"

  .form-group.save-button-album
    = f.submit t(:save), class: "save-button"
    - if (params[:action] == "edit")
      = link_to '<button class="delete-button" type="button">Delete</button>'.html_safe, album_path(album.id), method: :delete, data: { confirm: 'Are you sure?' }

app/views/albums/edit.html.slim
.container-fluid
  .row
    .col-md-10
      p.text-bold.edit-photo-content
        = t(:edit_album)
    .col-md-2
      = button_to t(:back), albums_path, method: :get, class: "button-back"
hr
.container-fluid
  = render "albums/form", album: @album

app/views/albums/index.html.slim
.add-new-album
  = button_to t(:add_new_album), new_album_path, method: :get, class: "button-add-album"
hr
.container-fluid
  .row
    - @albums.each do |album|
      -if album.photos.exists?
        .col-md-3.col-sm-4.col-6
          .post
            .post-album
              = image_tag album.photos.first.image_url(:thumb), class: "post-image-1"
              = image_tag album.photos.first.image_url(:thumb), class: "post-image-2"
              = image_tag album.photos.first.image_url(:thumb), class: "post-image-3"
              button.button-show-modal data-toggle="modal" data-target="#_#{album.id}"
            = image_tag "private-icon", class: "private-icon" if album.mode == "Private"
            .index-img-content
              .index-img-title
               = album.title
              .index-img-edit
                = link_to image_tag("edit-icon.png", class: "edit-icon"), edit_album_path(album.id)
            = image_tag album.photos.first.image_url(:thumb), class: "post-image-4"


        .modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" id="_#{album.id}" role="dialog" tabindex="-1"
          .modal-dialog role="document"
            .modal-content
              .modal-header
                h5#exampleModalLabel.modal-title
                  = album.title
                button.close aria-label="Close" data-dismiss="modal" type="button"
                  span aria-hidden="true"  ×
              .modal-body
                div id="carouselExampleControls_#{album.id}" class="carousel slide" data-ride="carousel"
                  .carousel-inner
                    - img = album.photos.sort_by {|record| record.updated_at}.reverse
                    .carousel-item.active
                      = image_tag img.first.image_url, class: "post-image"
                    - img.slice(1..-1).each do |img|
                      .carousel-item
                        = image_tag img.image_url, class: "post-image"
                  a.carousel-control-prev data-slide="prev" href="#carouselExampleControls_#{album.id}" role="button"
                    span.carousel-control-prev-icon aria-hidden="true"
                    span.sr-only Previous
                  a.carousel-control-next data-slide="next" href="#carouselExampleControls_#{album.id}" role="button"
                    span.carousel-control-next-icon aria-hidden="true"
                    span.sr-only Next
              .modal-footer
                = album.description
.page
  = paginate @albums

app/views/albums/new.html.slim
p.text-bold
  = t(:new_album)
hr

= render "albums/form", album: @album