config/routes.rb
Rails.application.routes.draw do

  root to: 'feeds#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums do
    resources :photos
  end
  resources :photos, :albums, :admins

end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  belongs_to :album, optional: true
  scope :public_mode, -> { where(mode: "Public") }
  validates :title, :description, :mode, presence: true
  validates :title, length: { maximum: 140,
    too_long: "Maximum 140 characters long" }
  validates :description, length: { maximum: 300,
    too_long: "Maximum 300 characters long" }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    if !current_user.admin
      @photos = current_user.photos.where.not("photos.title": "Image created from album!").page(params[:page])
    else
      @photos = Photo.where.not("photos.title": "Image created from album!").page(params[:page])
    end
  end

  def new
    @photo = Photo.new
  end

  def edit
    @photo = Photo.find(params[:id])
  end

  def create
    @photo = Photo.new(photo_params)
    @photo.user = current_user
    if @photo.save
      redirect_to photos_path
    else
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to photos_path
    else
      render 'edit'
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    redirect_to params[:redirect_path] || photos_path
  end

  private
    def photo_params
      params.require(:photo).permit(:title, :description, :mode, :image)
    end

end

app/views/photos/_form.html.slim
= form_for photo, html: { multipart: true } do |f|
  - if photo.errors.any?
    #error_explanation.alert.alert-warning.alert-dismissible.fade.show role="alert"
      h3
        = pluralize(photo.errors.count, "error")
        | prohibited this photo from being saved:
      ul
        - photo.errors.full_messages.each do |message|
          li= message
  .row
    .col-sm-6.col-12
      .form-group
        .text-bold
          = f.label t(:title)
        = f.text_field :title, placeholder: "Photo Title", class: "photo-title"

      .form-group
        .text-bold
          = f.label t(:mode)
        = f.select "mode",
          options_for_select([ "Public", "Private" ])

    .col-sm-6.col-12
      .form-group
        .text-bold
          = f.label t(:description)
        = f.text_area :description, rows: "4",placeholder: "Photo Description"

  .form-group.image-upload
    - if photo.image?
      = image_tag photo.image_url(:thumb), id: "img_prev", class: "img-thumbnail img-preview"
    -else
      = image_tag "plus-icon", id: "img_prev", class: "img-thumbnail img-preview"
    = f.file_field :image, onchange: "window.readURL(this);"
  .form-group
    = f.submit t(:save), class: "save-button"
    - if (params[:action] == "edit")
      = link_to '<button class="delete-button" type="button">Delete</button>'.html_safe, photo_path(photo.id), method: :delete, data: { confirm: 'Are you sure?' }

app/views/photos/edit.html.slim
.row
  .col-md-10
    p.text-bold.edit-photo-content
      = t(:edit_photo)
  .col-md-2
    = button_to t(:back), photos_path, method: :get, class: "button-back"
hr

= render "photos/form", photo: @photo

app/views/photos/index.html.slim
.add-new-photo
  = button_to t(:add_new_photo), new_photo_path, method: :get, class: "button-add-photo"
hr
.row
  - @photos.sort.each do |photo|
    .col-md-3.col-sm-4.col-6.post
      .index-img-content
        .index-img-title
         = photo.title
        .index-img-edit
          = link_to image_tag("edit-icon.png", class: "edit-icon"), edit_photo_path(photo.id)

      = image_tag photo.image_url(:thumb), class: "post-image"
      button.button-show-modal data-toggle="modal" data-target="#_#{photo.id}"

      = image_tag "private-icon", class: "private-icon" if photo.mode == "Private"

    .modal.fade aria-hidden="true" aria-labelledby="exampleModalLabel" id="_#{photo.id}" role="dialog" tabindex="-1"
      .modal-dialog role="document"
        .modal-content
          .modal-header
            h5#exampleModalLabel.modal-title
              = photo.title
            button.close aria-label="Close" data-dismiss="modal" type="button"
              span aria-hidden="true"  ×
          .modal-body
            = image_tag photo.image_url, class: "post-image"
          .modal-footer
            = photo.description

.page.text-center
  = paginate @photos

app/views/photos/new.html.slim
p.text-bold
  = t(:new_photo)
hr
= render "photos/form", photo: @photo