config/routes.rb
Rails.application.routes.draw do

  root to: 'feeds#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations', passwords: 'users/passwords' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :albums do
    resources :photos
  end
  resources :photos, :albums, :admins

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotobook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" >
    <meta content="width=device-width, initial-scale=1.0, viewport-fit=cover, maximum-scale=1.0, user-scalable=no" name="viewport" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render "shared/header" %>
    <%= render "shared/message" %>
    <div class="container-fluid bg">
      <div class="row">
        <div class="col-2">
          <div class="row">
            <div class="sidebar">
              <br>
              <% if !current_user.admin %>
                <div class="text-bold">
                  <%= link_to t(:feeds), root_path %>
                </div>
                <div class="text-bold">
                  <%= link_to t(:my_photos), photos_path%>
                </div>
                <div class="text-bold">
                  <%= link_to t(:my_albums), albums_path %>
                </div>
              <% else %>
                <div class="text-bold">
                  <%= link_to t(:feeds), root_path %>
                </div>
                <div class="text-bold">
                  <%= link_to t(:manage_photos), photos_path%>
                </div>
                <div class="text-bold">
                  <%= link_to t(:manage_albums), albums_path %>
                </div>
                <div class="text-bold">
                  <%= link_to t(:manage_users), admins_path %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-8 main-content">
          <%= yield %>
        </div>
        <div class="col-2"></div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fotobook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type" >
    <meta content="width=device-width, initial-scale=1.0, viewport-fit=cover, maximum-scale=1.0, user-scalable=no" name="viewport" >
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render "shared/header" %>
    <%= render "shared/message" %>

    <%= yield %>


  </body>
</html>